### ISSUE TITLE
init

### ISSUE THREAD

**Issue by GeneWu** [choupeiyuan/MPDA-ACA#1]
So far, what we are at:
-MACA
-OCDD

**Comment by choupeiyuan** [comment]
Hi, Gene. When I use "Iris" as an example to run your ACA algorithm, the output is : Optimal K=2, Attr2&Attr3 are selected as mode. And Attribute Groups are. Attr2/Attr1_Attr3_Attr4. Then, how to discretize for attributes? using equal frequency for Attr2 and Attr3 firstly? but how to determine the bins of equal frequency?

**Comment by choupeiyuan** [comment]
Hi, Gene. When I use "Iris" as an example to run your ACA algorithm, the
output is : Optimal K=2, Attr2&Attr3 are selected as mode. And Attribute
Groups are. Attr2/Attr1_Attr3_Attr4. Then, how to discretize for
attributes? using equal frequency for Attr2 and Attr3 firstly? but how to
determine the bins of equal frequency?

2015-06-25 17:31 GMT+08:00 GeneWu <notifications@github.com>:

**Comment by GeneWu** [comment]
rule of thumb

**Comment by GeneWu** [comment]
I just think of a heuristics:
In the group if the mode is continuous, for all discrete attribute, find the b = max(count the number of discrete value). Then, use the b as the number of bins for equal frequency.
